/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.livre;

import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author Puteaux
 */
public class AffichageLivre extends javax.swing.JPanel {
    
    private JFrame jf;

    public JFrame getJf() {
        return jf;
    }

    public void setJf(JFrame jf) {
        this.jf = jf;
    }

    /**
     * Creates new form AffichageLivre
     */
    public AffichageLivre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        boutonAjouter = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        boutonSupprimer.setText("Supprimer");
        add(boutonSupprimer);
        boutonSupprimer.setBounds(550, 500, 90, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 1100, 360);

        jButton1.setText("jButton1");
        add(jButton1);
        jButton1.setBounds(280, 500, 77, 32);

        boutonAjouter.setText("Ajouter");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });
        add(boutonAjouter);
        boutonAjouter.setBounds(70, 490, 71, 32);

        jButton3.setText("jButton3");
        add(jButton3);
        jButton3.setBounds(430, 500, 77, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed
        // TODO add your handling code here:
        AjouterLivre ajout = new AjouterLivre((Frame) this.getTopLevelAncestor(), true);
        ajout.setVisible(true);
    }//GEN-LAST:event_boutonAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjouter;
    private javax.swing.JButton boutonSupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
