/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.livre;

import classe.Auteur;
import gestion.GestionAuteur;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import util.BdDConnexion;

/**
 *
 * @author Puteaux
 */
public class AjouterAuteur extends javax.swing.JDialog {

    private Connection connexion = null;
    private BdDConnexion bdDConnexion = new BdDConnexion();
    private GestionAuteur gestion;
    private Auteur auteur;

    /**
     * Creates new form AjouterAuteur
     */
    public AjouterAuteur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        connexion = bdDConnexion.connectDataBase();
        gestion = new GestionAuteur(connexion);
        initComponents();
        listeAuteur.setModel(initListeAuteur());
//        listeAuteur.setSelectedIndex(0);
    }

    public DefaultListModel initListeAuteur() {
        DefaultListModel model = new DefaultListModel();
        try {
            ResultSet rs = gestion.sqlRead();
            while (rs.next()) {
                model.addElement(new Auteur(rs.getInt("idAuteur"), rs.getString("nomAuteur"), rs.getString("prenomAuteur")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AjouterAuteur.class.getName()).log(Level.SEVERE, null, ex);
        }
        return model;
    }

    public Auteur getAuteur() {
        return auteur;
    }

    public void setAuteur(Auteur auteur) {
        this.auteur = auteur;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeAuteur = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        boutonValider = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textNomAuteur = new javax.swing.JTextField();
        textePrenomAuteur = new javax.swing.JTextField();
        labelNomAuteur = new javax.swing.JLabel();
        labelPrenomAuteur = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        listeAuteur.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listeAuteur);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 220, 147);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 120, 41, 16);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 80, 41, 16);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 300, 77, 32);

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });
        getContentPane().add(boutonValider);
        boutonValider.setBounds(250, 390, 120, 60);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 30, 41, 16);
        getContentPane().add(textNomAuteur);
        textNomAuteur.setBounds(410, 160, 190, 30);
        getContentPane().add(textePrenomAuteur);
        textePrenomAuteur.setBounds(410, 200, 190, 30);

        labelNomAuteur.setText("Nom");
        getContentPane().add(labelNomAuteur);
        labelNomAuteur.setBounds(366, 160, 30, 16);

        labelPrenomAuteur.setText("Prenom");
        getContentPane().add(labelPrenomAuteur);
        labelPrenomAuteur.setBounds(350, 210, 50, 16);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 240, 77, 32);

        setSize(new java.awt.Dimension(685, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        auteur = (Auteur) listeAuteur.getSelectedValue();
        dispose();
    }//GEN-LAST:event_boutonValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterAuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterAuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterAuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterAuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterAuteur dialog = new AjouterAuteur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonValider;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNomAuteur;
    private javax.swing.JLabel labelPrenomAuteur;
    private javax.swing.JList listeAuteur;
    private javax.swing.JTextField textNomAuteur;
    private javax.swing.JTextField textePrenomAuteur;
    // End of variables declaration//GEN-END:variables
}
