/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.livre;

import classe.Editeur;
import gestion.GestionEditeur;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import util.BdDConnexion;

/**
 *
 * @author Puteaux
 */
public class AjouterEditeur extends javax.swing.JDialog {

    private GestionEditeur gestion;
    private Connection connexion;
    private BdDConnexion BDDcon = new BdDConnexion();
    private Editeur editeur;
    private TableRowSorter sorter;

    public Editeur getEditeur() {
        return editeur;
    }

    public void setEditeur(Editeur editeur) {
        this.editeur = editeur;
    }

    /**
     * Creates new form AjouterEditeur
     */
    public AjouterEditeur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        connexion = BDDcon.connectDataBase();
        gestion = new GestionEditeur(connexion);
        initComponents();
        sorter = new TableRowSorter(tableEditeur.getModel());
        tableEditeur.setRowSorter(sorter);
    }

    public DefaultTableModel initTableEditeur() {
        Vector vData = new Vector();
        Vector vNoms = new Vector();
        vNoms.addElement("Editeur");
        try {
            ResultSet rs = gestion.sqlRead();
            while (rs.next()) {
                Vector vLigne = new Vector();
                vLigne.addElement(new Editeur(rs.getString(1)));
                vData.add(vLigne);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            if (ex.getErrorCode() == 2627) {
                JOptionPane.showMessageDialog(this, "Editeur déjà présent dans la Base de Données", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        return new DefaultTableModel(vData, vNoms);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEditeur = new javax.swing.JTable();
        champAjouterEditeur = new javax.swing.JTextField();
        champRecherche = new javax.swing.JTextField();
        labelAjouterEditeur = new javax.swing.JLabel();
        boutonAjouterEditeur = new javax.swing.JButton();
        boutonValider = new javax.swing.JButton();
        labelRechercher = new javax.swing.JLabel();
        boutouRechercher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tableEditeur.setModel(initTableEditeur());
        jScrollPane1.setViewportView(tableEditeur);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 210, 270);
        getContentPane().add(champAjouterEditeur);
        champAjouterEditeur.setBounds(300, 90, 160, 30);
        getContentPane().add(champRecherche);
        champRecherche.setBounds(30, 90, 160, 30);

        labelAjouterEditeur.setText("Ajouter un Editeur");
        getContentPane().add(labelAjouterEditeur);
        labelAjouterEditeur.setBounds(300, 60, 110, 16);

        boutonAjouterEditeur.setText("Ajouter");
        boutonAjouterEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterEditeurActionPerformed(evt);
            }
        });
        getContentPane().add(boutonAjouterEditeur);
        boutonAjouterEditeur.setBounds(390, 130, 71, 32);

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });
        getContentPane().add(boutonValider);
        boutonValider.setBounds(200, 440, 90, 50);

        labelRechercher.setText("Rechercher");
        getContentPane().add(labelRechercher);
        labelRechercher.setBounds(30, 60, 70, 16);

        boutouRechercher.setText("Ok");
        boutouRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutouRechercherActionPerformed(evt);
            }
        });
        getContentPane().add(boutouRechercher);
        boutouRechercher.setBounds(200, 90, 50, 32);

        setSize(new java.awt.Dimension(540, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonAjouterEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterEditeurActionPerformed
        // TODO add your handling code here:
        if (!champAjouterEditeur.getText().trim().isEmpty()) {
            try {
                editeur = new Editeur(champAjouterEditeur.getText());
                gestion.sqlCreate(editeur);
                tableEditeur.setModel(initTableEditeur());
            } catch (SQLException ex) {
                System.out.println(ex);
                if (ex.getErrorCode() == 2627) {
                    JOptionPane.showMessageDialog(this, "Editeur déjà présent dans la Base de Données", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_boutonAjouterEditeurActionPerformed

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        if (tableEditeur.getSelectedRow() > -1) {
            editeur = (Editeur) tableEditeur.getValueAt(tableEditeur.getSelectedRow(), 0);
            dispose();
        }
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void boutouRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutouRechercherActionPerformed
        // Row filter qui filtre le table model selon une regex
        // regex : (?iu) permet d'ignorer la case et les accents
        RowFilter<DefaultTableModel, Editeur> rf = null;
        try {
            rf = RowFilter.regexFilter("(?iu)" + champRecherche.getText());
        } catch (java.util.regex.PatternSyntaxException e) {
            System.out.println("erreur saisie");
            return;
        }
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_boutouRechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterEditeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterEditeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterEditeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEditeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterEditeur dialog = new AjouterEditeur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjouterEditeur;
    private javax.swing.JButton boutonValider;
    private javax.swing.JButton boutouRechercher;
    private javax.swing.JTextField champAjouterEditeur;
    private javax.swing.JTextField champRecherche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAjouterEditeur;
    private javax.swing.JLabel labelRechercher;
    private javax.swing.JTable tableEditeur;
    // End of variables declaration//GEN-END:variables
}
